"""Add metadata_blob

Revision ID: 9e4fd95e2cf8
Revises: caf637a70c39
Create Date: 2026-09-05 13:22:46.009788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4fd95e2cf8'
down_revision: Union[str, Sequence[str], None] = 'caf637a70c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_decisions', sa.Column('metadata_blob', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_decisions', 'metadata_blob')
    # ### end Alembic commands ###
