"""Security hardening

Revision ID: befc6b07d5af
Revises: dcd11cc3924c
Create Date: 2026-08-29 12:51:11.517661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befc6b07d5af'
down_revision: Union[str, Sequence[str], None] = 'dcd11cc3924c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue_risk_cases', sa.Column('amount_recovered', sa.BigInteger(), server_default='0', nullable=False))
    op.create_index(op.f('ix_revenue_risk_cases_customer_id'), 'revenue_risk_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_revenue_risk_cases_id'), 'revenue_risk_cases', ['id'], unique=False)
    op.create_check_constraint('check_amount_at_risk_positive', 'revenue_risk_cases', 'amount_at_risk >= 0')
    op.create_check_constraint('check_amount_recovered_positive', 'revenue_risk_cases', 'amount_recovered >= 0')
    op.create_check_constraint('check_attempt_count_positive', 'revenue_risk_cases', 'attempt_count >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_attempt_count_positive', 'revenue_risk_cases', type_='check')
    op.drop_constraint('check_amount_recovered_positive', 'revenue_risk_cases', type_='check')
    op.drop_constraint('check_amount_at_risk_positive', 'revenue_risk_cases', type_='check')
    op.drop_index(op.f('ix_revenue_risk_cases_id'), table_name='revenue_risk_cases')
    op.drop_index(op.f('ix_revenue_risk_cases_customer_id'), table_name='revenue_risk_cases')
    op.drop_column('revenue_risk_cases', 'amount_recovered')
    # ### end Alembic commands ###
