"""Add RBAC and constraints

Revision ID: c88e78fbc278
Revises: befc6b07d5af
Create Date: 2026-08-29 13:25:52.980191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88e78fbc278'
down_revision: Union[str, Sequence[str], None] = 'befc6b07d5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_check_constraint('check_decision_cost_positive', 'case_decisions', 'cost >= 0')
    op.create_check_constraint('check_decision_friction_positive', 'case_decisions', 'friction >= 0')
    op.create_check_constraint('check_decision_prob_bounds', 'case_decisions', 'success_probability >= 0.0 AND success_probability <= 1.0')
    op.create_check_constraint('check_decision_risk_positive', 'case_decisions', 'risk >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_decision_risk_positive', 'case_decisions', type_='check')
    op.drop_constraint('check_decision_prob_bounds', 'case_decisions', type_='check')
    op.drop_constraint('check_decision_friction_positive', 'case_decisions', type_='check')
    op.drop_constraint('check_decision_cost_positive', 'case_decisions', type_='check')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
