"""Initial domain models

Revision ID: dcd11cc3924c
Revises: 
Create Date: 2026-08-28 13:06:51.802446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd11cc3924c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_risk_cases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('amount_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSESSING', 'EXECUTING', 'WAITING_FOR_APPROVAL', 'WAITING_FOR_OUTCOME', 'RECOVERED', 'ESCALATED', 'STOPPED', name='casestatus'), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('recovery_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('metadata_blob', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['revenue_risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_actions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('provider_reference_id', sa.String(length=100), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['revenue_risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('case_decisions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('expected_value', sa.BigInteger(), nullable=False),
    sa.Column('success_probability', sa.Float(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('friction', sa.BigInteger(), nullable=False),
    sa.Column('risk', sa.BigInteger(), nullable=False),
    sa.Column('final_enr', sa.BigInteger(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('policy_rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['revenue_risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_references',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['revenue_risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('action_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewer_id', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['case_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approvals')
    op.drop_table('payment_references')
    op.drop_table('case_decisions')
    op.drop_table('case_actions')
    op.drop_table('audit_events')
    op.drop_table('webhook_events')
    op.drop_table('revenue_risk_cases')
    # ### end Alembic commands ###
