from enum import Enum

class ErrorCode(str, Enum):
    # Razorpay Errors
    RAZORPAY_AUTH_ERROR = "RAZORPAY_AUTH_ERROR"
    RAZORPAY_RATE_LIMIT = "RAZORPAY_RATE_LIMIT"
    RAZORPAY_TIMEOUT = "RAZORPAY_TIMEOUT"
    RAZORPAY_SERVER_ERROR = "RAZORPAY_SERVER_ERROR"
    
    # Webhook Errors
    WEBHOOK_INVALID_SIGNATURE = "WEBHOOK_INVALID_SIGNATURE"
    WEBHOOK_MISSING_SIGNATURE = "WEBHOOK_MISSING_SIGNATURE"
    WEBHOOK_MISSING_EVENT_ID = "WEBHOOK_MISSING_EVENT_ID"
    WEBHOOK_DUPLICATE_EVENT = "WEBHOOK_DUPLICATE_EVENT"
    
    # Domain Errors
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    CASE_NOT_FOUND = "CASE_NOT_FOUND"
    ACTION_NOT_ALLOWED = "ACTION_NOT_ALLOWED"
    ECONOMIC_CONSTRAINT_VIOLATION = "ECONOMIC_CONSTRAINT_VIOLATION"
    
    # System Errors
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
